# Generated by Django 4.0.2 on 2022-06-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='anonoymous',
            new_name='anonymous',
        ),
    ]
